### Configuration File for CIBR-FLARE Project
## General Settings
git:
  remote:
    server: github.com
    branch: master
    ssh-key-private: /root/.ssh/id_rsa
    user-name: Jyuqi
    user-email: jinyuqi@ufl.edu
## Container Settings
container:
  name: flare-visualize
  version: 21.01.2
  working-directory:
    pre-run-pull: FALSE
    post-run-push: FALSE
    git:
      remote:
        server: 192.168.20.20
        port:
        repository: FLARE-forecast/test-data
        branch: master
        directory: fcre
## Container Paths
flare_path: /root/flare
flare_shared_path: /root/flare/shared
qaqc_data_location: /root/flare/shared/flare-process-observations/fcre-processed-observations
lakes_directory: flare_lake_examples
forecast_location: /root/flare/shared/flare-generate-forecast/forecast
run_config: /root/flare/shared/flare-generate-forecast/forecast/configuration_files/run_configuration.yml
## Lake Information
lake_name_code: fcre
lake_name: Falling Creek Reservoir
## Openwhisk Settings
openwhisk:
  days-look-back: 0
  container-dependencies: "flare-generate-forecast"
  next-trigger:
    name: flare-visualize-ready-fcre
    payload: '{"type":"payload"}'